version: '3'
services:
  dokgen:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "5914:8080"
    volumes:
      - ./content:/app/content
      - ./logs:/secure-logs
    environment:
      RUNTIME_OPTS: "--write.access=true"