apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-dokgen
  namespace: default
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /actuator/info
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  readiness:
    path: /actuator/health
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  leaderElection: false
  prometheus:
    enabled: true
    path: /actuator/metrics/prometheus
  istio:
    enabled: false
  resources:
    limits:
      cpu: "1000m"
      memory: "2048Mi"
    requests:
      cpu: "100m"
      memory: "1024Mi"
  logformat: accesslog
  logtransform: dns_loglevel
  webproxy: false
  vault:
    enabled: false
  env:
    - name: APP_TEAM
      value: teamfamilie