name: Bygg og deploy

on:
  push:
    branches:
      - master         # Push events on master branch
env:
  IMAGE: ghcr.io/${{ github.repository }}/familie-ba-dokgen:${{ github.sha }}
  IMAGE_TAG_LATEST: ghcr.io/${{ github.repository }}/familie-ba-dokgen:latest

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Bygg docker image"
    steps:
      - uses: actions/checkout@v1

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg og push docker-image
        uses: docker/build-push-action@v2
        with:
          tags: |
            ${{ env.IMAGE }}
            ${{ env.IMAGE_TAG_LATEST }}
          pull: true
          push: true

  deploy-preprod:
    runs-on: ubuntu-latest
    name: Deploy to preprod
    needs: build
    steps:
      - uses: actions/checkout@v1

      - name: Deploy to GCP dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais.yaml
          VARS: .deploy/dev-gcp-vars.yaml

  deploy-prod:
    runs-on: ubuntu-latest
    name: Deploy to prod
    needs: build
    steps:
      - uses: actions/checkout@v1

      - name: Deploy to GCP PROD
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais.yaml
          VARS: .deploy/prod-gcp-vars.yaml
