name: Bygg og deploy

on:
  push:
    branches:
      - main         # Push events on master branch

jobs:
  bygg:
    name: Bygg app/image og push til GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamfamilie
          push_image: true
          dockerfile: Dockerfile
          docker_context: .
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
  deploy-preprod:
    name: Deploy til dev-gcp
    needs:
      - bygg
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - name: Deploy til dev-gcp team namespace
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/naiserator-preprod.yaml
          IMAGE: ${{ needs.bygg.outputs.image }}

  deploy-prod:
    name: Deploy til prod-gcp
    needs:
      - bygg
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - name: Deploy til prod-gcp team namespace
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .deploy/naiserator-prod.yaml
          IMAGE: ${{ needs.bygg.outputs.image }}
